version: '3'

services:
  app:
    build: .
    entrypoint: ".docker/entrypoint.sh"
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000 
    depends_on:
      - mongodb  
    extra_hosts:
      - host.docker.internal:192.168.1.106
      
  mongodb:
    image: mongo:5.0.5
    restart: always
    volumes:
      - ./.docker/dbdata:/data/db
      - ./.docker/mongo:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=analytics

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    depends_on:
      - mongodb
    # networks:
    #   - full_cycle    

  redis:
    image: redis:6.2.6-alpine3.14
# tweets - Apache Kafka - JSON -> NoSQL

# networks:
#   full_cycle:
#     name: full_cycle
  